[PMM-6756] add go 1.15
percona/pmm-update pull request #109
Opened 2020-10-13 12:09 UTC by yareach

2020-10-13 12:09 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pmm-update?pullRequest=109) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm-update?pullRequest=109) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm-update?pullRequest=109) it.</sub>

2020-10-19 14:47 UTC, adivinho commented
Could it be rebased to "release/2.12" ?

2020-10-20 09:37 UTC, adivinho requested changes
Could it be rebased to "release/2.12" ?

2020-10-21 10:47 UTC, adivinho approved these changes

2020-10-21 12:09 UTC, BupycHuk approved these changes

2020-10-21 12:09 UTC, merged