Update CODEOWNERS
percona/pmm-update pull request #241
Opened 2022-09-13 09:26 UTC by BupycHuk

PMM-7

Build: SUBMODULES-0

- [ ] Links to other linked pull requests (optional).

2022-09-13 09:35 UTC, nikita-b approved these changes

2022-09-15 09:49 UTC, atymchuk requested changes
Can we add @talhabinrizwan to the list?

2022-09-15 09:50 UTC, BupycHuk commented
@atymchuk done

2022-09-15 09:50 UTC, atymchuk approved these changes

2022-09-15 09:50 UTC, merged