PMM-11126 PMM server cannot be updated to 2.32.0
percona/pmm-update pull request #256
Opened 2022-11-22 14:40 UTC by cezmunsta

The nginx package is excluded from the updated, but related packages may have an update available and so they need to be excluded too.

[PMM-11126](https://jira.percona.com/browse/PMM-11126)

Build: [SUBMODULES-2910](https://github.com/Percona-Lab/pmm-submodules/pull/2910)

2022-11-22 15:39 UTC, atymchuk requested changes

2022-11-22 15:39 UTC, atymchuk commented on ansible/playbook/tasks/update.yml
> +          - 'nginx*'
```suggestion
          - "nginx*"
```
Seems like we use double quotes everywhere.

2022-11-22 16:08 UTC, michal-kralik approved these changes

2022-11-23 09:31 UTC, atymchuk commented on ansible/playbook/tasks/update.yml
> +          - 'nginx*'
I see, but then it's not consistent with the rest of the code in the same file. Do you want to replace double quotes with single quotes everywhere?

2022-11-23 09:39 UTC, atymchuk approved these changes

2022-11-28 14:20 UTC, merged